## Q1- construct 1d numpy array, 2d numpy array,3d numpy array.


In [22]:
import numpy as np


array_1d = np.array([1,2,3])
array_2d = np.array([[1,2,3],[2,5,8]])
array_3d = np.array([[[11,41],[12,0]],[[11,41],[12,0]]])

print('shape = ',array_1d.shape,'num of dimentions = ',array_1d.ndim)
print('shape = ',array_2d.shape,'num of dimentions = ',array_2d.ndim)
print('shape = ',array_3d.shape,'num of dimentions = ',array_3d.ndim)


(3,) 1
(2, 3) 2
(2, 2, 2) 3


## Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()


In [2]:
arr= np.array([1,2,3])
zero_array = np.zeros(5)

print(np.any(arr))
print(np.any(zero_array))

True
False


### Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.


In [5]:
zero_array = np.zeros(10)
one_array = np.ones(10)
five_array = np.full(10,5)

print(zero_array)
print(one_array)
print(five_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


### Q4- Write a NumPy program to create an array of 10 zeros 3d


In [8]:
zero_array = np.zeros((2,1,5))

print(zero_array)
print('='*50)
zero_array2 = np.zeros((10)).reshape(2,1,5)

print(zero_array2)

[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]
[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


### Q5- Write a NumPy program to create an array of the integers from 30 to 70.


In [9]:
arr= np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### Q6- Write a NumPy program to create a 3x3 identity matrix.


In [16]:
identity_matrix= np.eye(3,3)

print(identity_matrix)

print(np.identity((3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q7- Write a NumPy program to generate a random number between 0 and 1.


In [19]:
arr = np.random.rand()
print(arr)

0.33271224970074587


### Q8- Write a NumPy program to create a 3X4 array using and iterate over it.

In [25]:
arr = np.random.randint(1,20,(3,4))

print("Original array:")
print(arr)
print("Each element of the array is:")
for x in np.nditer(arr):
    print(x,end=" ")


Original array:
[[ 1  7  2  8]
 [ 5  3 11 10]
 [ 2  2  8 17]]
Each element of the array is:
1 7 2 8 5 3 11 10 2 2 8 17 

### Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [30]:
arr = np.ones((10,10))
arr [1:-1,1:-1] = np.zeros((arr [1:-1,1:-1].shape))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


(8, 8)